Fix missing math function warnings in Machinekit
Machinekit normally provides `rtapi_pow()` and `rtapi_fabs()`.  For
LCNC math compatibility, Machinekit provides those when a
`LCNC_COMPAT` macro is set.

    lcec_ax5200.c: In function ‘lcec_ax5200_init’:
    lcec_ax5200.c:201:50: warning: implicit declaration of function ‘pow’ [-Wimplicit-function-declaration]
	 chan->vel_scale = ((double) idn_vel_scale) * pow(10.0, (double) idn_vel_exp);
						      ^~~
    lcec_ax5200.c:201:50: warning: incompatible implicit declaration of built-in function ‘pow’
    lcec_ax5200.c:201:50: note: include ‘<math.h>’ or provide a declaration of ‘pow’
    lcec_ax5200.c:23:1:
    +#include <math.h>

    lcec_ax5200.c:201:50:
	 chan->vel_scale = ((double) idn_vel_scale) * pow(10.0, (double) idn_vel_exp);
						      ^~~