Fix build on Machinekit
    In file included from lcec_conf.c:30:
    lcec_conf.c: In function ‘main’:
    lcec_rtapi.h:31:43: error: too many arguments to function ‘rtapi_shmem_getptr’
      #define lcec_rtapi_shmem_getptr(id, ptr) rtapi_shmem_getptr(id, ptr, NULL)
					       ^~~~~~~~~~~~~~~~~~

It looks like the `rtapi_shmem_getptr(id, ptr, NULL)` signature (with
its third parameter) was added to accommodate Machinekit, whose RTAPI
API was changed after forking from LinuxCNC.  This change has since
been reverted in rev.  32966a2245a45c6bb41f94de276b12ebfea45eb0.